CREATE TABLE public.task (
  id              INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  todo_id         INT NOT NULL,
  parent_id       INT,
  title           TEXT NOT NULL,
  notes           TEXT,
  created_date    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_date    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT fk_todo_id FOREIGN KEY (todo_id)
    REFERENCES public.todo (id) ON DELETE RESTRICT,
  CONSTRAINT fk_task_parent_id FOREIGN KEY (parent_id)
    REFERENCES public.task (id) ON DELETE RESTRICT
);

CREATE INDEX idx_task_todo_id ON public.task(todo_id);
CREATE INDEX idx_task_parent_id on public.task(parent_id);
