CREATE TABLE public.todo (
  id              INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid            TEXT NOT NULL,
  title           TEXT NOT NULL,
  created_date    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_date    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_todo_uuid ON public.todo(uuid);
