
/**
 * AUTO-GENERATED FILE @ Fri, 29 Mar 2024 07:54:47 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.1.0.8
 * $ schemats generate postgres://username:password@ep-black-resonance-a2r61o8a.eu-central-1.aws.neon.tech:5432/verceldb -s public
 *
 */

export type Status = 'IN_PROGRESS' | 'DONE'

export interface Todo { 
  id: number
  uuid: string
  title: string
  created_date: Date
  updated_date: Date 
}

export interface Task { 
  id: number
  todo_id: number
  parent_id?: number | null
  title: string
  notes?: string | null
  created_date: Date
  updated_date: Date
  status: Status 
}

export interface Migrations { 
  id: number
  name: string
  run_on: Date 
}

export interface Tables {
  todo: Todo,
  task: Task,
  migrations: Migrations
}